apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
  namespace: drkiq
spec:
  replicas: 1
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.0.5
        resources: {}
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data

  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi