apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: drkiq
type: Opaque
data:
  database_url: "cG9zdGdyZXNxbDovL2Rya2lxOnlvdXJwYXNzd29yZEBwb3N0Z3Jlc3FsOjU0MzIvZHJraXE/ZW5jb2Rpbmc9dXRmOCZwb29sPTUmdGltZW91dD01MDAwCg=="
  postgres_user: "ZHJraXE="
  postgres_password: "eW91cnBhc3N3b3Jk"