apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: drkiq
spec:
  replicas: 1
  serviceName: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:9.4.5
        resources: {}
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: postgres_user
                name: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres_password
                name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
            subPath: postgres

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi