apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: drkiq
type: Opaque
data:
  database_url: "cG9zdGdyZXNxbDovL2Rya2lxOnlvdXJwYXNzd29yZEBwb3N0Z3Jlc3FsOjU0MzIvZHJraXE/ZW5jb2Rpbmc9dXRmOCZwb29sPTUmdGltZW91dD01MDAwCg=="
  postgres_user: "ZHJraXE="
  postgres_password: "eW91cnBhc3N3b3Jk"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: drkiq
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: postgres_user
                name: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres_password
                name: postgres
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
            subPath: postgres

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}