apiVersion: v1
kind: Service
metadata:
  labels:
    app: drkiq
  name: drkiq
  namespace: drkiq
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app: drkiq
  type: NodePort
